DZ path 6
alexieze/test-guru pull request #5
Opened 2018-03-23 18:39 UTC by alexieze

2018-03-23 19:15 UTC, vkurennov requested changes

2018-03-23 19:15 UTC, vkurennov commented on app/models/answer.rb
> +  scope :correct, -> { where(correct: 1) }
Используй true/false для булевых атибутов.

2018-03-23 19:15 UTC, vkurennov commented on app/models/question.rb
> +  validates :answers, length: { maximum: 4 }
Валидация length не работает для ассоциаций, она работает только для строк, тут нужна кастомная валидация

2018-03-24 18:40 UTC, vkurennov approved these changes

2018-03-24 18:40 UTC, vkurennov commented on app/models/question.rb
> +  validates :answers, length: { maximum: 4 }
Удали эту ассоциаицю, она же не работает.

2018-03-25 05:05 UTC, alexieze commented on app/models/question.rb
> +  validates :answers, length: { maximum: 4 }
Что-то пропустил, удалил.

2018-03-25 05:05 UTC, merged